language: cpp
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
      - build-essential git cmake libfreeimage-dev
      - cmake-curses-gui
      - libopenblas-dev libfftw3-dev liblapacke-dev
      - libboost-all-dev
      - opencl-headers
      - libglfw3-dev libfontconfig1-dev
script:
  - git clone https://github.com/arrayfire/arrayfire.git
  - cd arrayfire
  - git submodule init
  - git submodule update
  - mkdir build; cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make; make install
#  - cd ../../pytorch-inference
#  - mkdir build; cd build
#  - cmake --build . --target test_all -- -j 4
compiler:
  - gcc
  - clang
os:
  - osx
  - linux
branches:
  only:
    - master
    - dev